runtime: nodejs14

inbound_services:
- warmup

service: default

handlers:
- url: /static
  static_dir: dist/static
  secure: always

- url: /(.*\.(ico|png))$
  static_files: dist/static/\1
  upload: static/.*\.(ico|png)$
  secure: always

- url: /.*
  script: auto
  secure: always
  
env_variables:
     MAPS_KEY: $MAPS_KEY
     DARKSKY_API_KEY: $DARKSKY_KEY
     RWGPS_API_KEY: $RWGPS_KEY
     STRAVA_API_KEY: $STRAVA_KEY
     TIMEZONE_API_KEY: $TIMEZONE_KEY
     CLIMACELL_KEY: $CLIMACELL_KEY
     WEATHER_API_KEY: $WEATHERAPI_KEY
     BITLY_TOKEN: $BITLY_TOKEN
     STRAVA_CLIENT_ID: $STRAVA_CLIENT_ID
     VISUAL_CROSSING_KEY: $VISUAL_CROSSING_KEY
     PURPLE_AIR_KEY: $PURPLE_AIR_KEY
     IQAIR_KEY: $IQAIR_KEY
     RWGPS_OAUTH_CLIENT_ID: $RWGPS_OAUTH_CLIENT_ID
     RWGPS_OAUTH_SECRET: $RWGPS_OAUTH_SECRET
