# This is a basic workflow to help you get started with Actions

name: Publish to Google app Engine

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      MAPS_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}     
      - name: Install Packages
        run: npm install
      - name: Install Sentry client
        run: npm install @sentry/cli
      - name: Get Sentry version
        run: VERSION=$(./node_modules/.bin/sentry-cli releases propose-version)
      - name: Build page
        run: npm run prod --env sentryRelease=$VERSION        
      - name: Initialize Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true        
      - name: Secrets
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          MAPS_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          DARKSKY_KEY: ${{ secrets.DARKSKY_API_KEY }}  
          RWGPS_KEY: ${{ secrets.RWGPS_API_KEY }}  
          STRAVA_KEY: ${{ secrets.STRAVA_API_KEY }}  
          TIMEZONE_KEY: ${{ secrets.TIMEZONE_KEY }}  
          CLIMACELL_KEY: ${{ secrets.CLIMACELL_KEY }}  
          WEATHERAPI_KEY: ${{ secrets.WEATHER_API_KEY }}  
          BITLY_TOKEN: ${{ secrets.BITLY_TOKEN }}  
          STRAVA_CLIENT_ID:  ${{ secrets.STRAVA_CLIEBT_ID }}  
      - name: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}  
          version: current
